### ISSUE TITLE
再贡献个makefile文件吧

### ISSUE THREAD

**Issue by iphyer** [LePtC/LeNote#2]
再贡献个makefile文件吧
不过我实在Linux下测试过，不知道windows怎么用。你看看是不是可以自己调整。
make all这个命令就可以完成全部的任务，清除temp文件和打开阅读文件。

Makefile:
# 该 Makefile 用于编译一个 Beamer 制作的幻灯片
# 运行环境：Linux、texlive2010(XeTeX)、evince 阅读器

Compiler = xelatex
Reader = evince

Target = LePtC.pdf
Source = LePtC.tex
TmpFile = *.out *.log *.aux *.nav *.snm *.toc *.synctex.gz

$(Target): $(Source)
    $(Compiler) --quiet --synctex=1 -interaction=nonstopmode $(Source)
    $(Compiler) --quiet --synctex=1 -interaction=nonstopmode $(Source)

all: $(Target) clean read 

read:
    $(Reader) $(Target)

clean:
    -rm $(TmpFile)

cleanall:
    -rm $(TmpFile) $(Target)

.PHONY: all read clean cleanall

**Comment by iphyer** [comment]
```
# 该 Makefile 用于编译一个 Beamer 制作的幻灯片
# 运行环境：Linux、texlive2010(XeTeX)、evince 阅读器

Compiler = xelatex
Reader = evince

Target = LePtC.pdf
Source = LePtC.tex
TmpFile = *.out *.log *.aux *.nav *.snm *.toc *.synctex.gz

$(Target): $(Source)
    $(Compiler) --quiet --synctex=1 -interaction=nonstopmode $(Source)
    $(Compiler) --quiet --synctex=1 -interaction=nonstopmode $(Source)

all: $(Target) clean read 

read:
    $(Reader) $(Target)

clean:
    -rm $(TmpFile)

cleanall:
    -rm $(TmpFile) $(Target)

.PHONY: all read clean cleanall
```

**Comment by iphyer** [comment]
Sorry刚刚忽略了markdown格式的问题

**Comment by LePtC** [comment]
感谢~我等会把链接加到说明页面里~

**Comment by iphyer** [comment]
好的！
解决了问题就把issue报告close吧。
这样别人就知道你解决了这个bug。
