### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by PokerN** [LePtC/LeNote#4]
您好，很高兴看到你设计了这么好的笔记模板。

在编译过程中，发现缺少一些字体，不知能否上传模板中所用到的字体文件呢？
（比如：锐字云字库准圆体GBK）

另外：我的系统是mac os，用的版本是 mactex 2016，在编译过程中，
发现 dtklogos.sty 找不到，查找后发现对应的文件名应该是：
dtk-logos.sty
不知是否是版本更新的缘故，还是系统的缘故。更改完后，可顺利编译。

**Comment by LePtC** [comment]
感谢反馈～

的确是 dtk-logos.sty，这个 bug 下一版会修复
下一版会把准圆字体改成更常见的方正准圆GBK

（最近电脑重装了…要过一段时间才能更新…）

**Comment by LePtC** [comment]
update 2016.11 已解决
